//RATING
export const SET_RATING_LIST = "SET_RATING_LIST";
export const SET_RATING_DETAILS = "SET_RATING_DETAILS";
export const SET_CREATED_RATING_DATA = "SET_CREATED_RATING_DATA";
export const SET_UPDATED_RATING_DATA = "SET_UPDATED_RATING_DATA";
export const SET_DELETED_RATING_DATA = "SET_DELETED_RATING_DATA";